language: php

sudo: false

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1

env:
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

install:
    - composer update $DEFAULT_COMPOSER_FLAGS

script: vendor/bin/phpunit --verbose
